import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";

import Link from "next/link";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="mx-auto min-h-screen max-w-1920">{children}</div>
        <Footer />
        <div className="flex h-[70px] items-center justify-center space-x-4 text-sm bg-black text-white">
          Copyright © 1989 - 2024 MAGIC Foundation
          <div></div>
          {/* <Separator className="h-[20px]" orientation="vertical"></Separator> */}
          <Link className="text-primaryLink" href={`/`}>
            Disclaimer
          </Link>
          {/* <Separator className="h-[20px]" orientation="vertical"></Separator> */}
          <Link className="text-primaryLink" href={`/`}>
            Privacy
          </Link>
          {/* <Separator className="h-[20px]" orientation="vertical"></Separator> */}
          <Image src={"/phone.png"} width={20} height={20} alt="phone" />
          <Link className="text-primaryLink" href={`/`}>
            Call Us 800-362-4423
          </Link>
        </div>{" "}
      </body>
    </html>
  );
}
